added date functin for automatic date updates
SU-UTB/web-majales-2023 pull request #10
Opened 2023-10-20 12:35 UTC by WilloS88

2023-10-20 13:07 UTC, SedlarDavid commented
V souboru public/index.html je v headu stále rok 2023

2023-10-20 13:09 UTC, SedlarDavid requested changes
viz předchozí comment

2023-10-20 14:21 UTC, tomesfilip requested changes
okay, in public files (like index.html) we need to use hardcoded value. maybe for the sake of simplicity, let's use the hardcoded 2024 value everywhere. This will be changed in the new repo.

2023-10-20 14:21 UTC, tomesfilip commented on index.html
> +    <title></title>
missing title

2023-10-20 14:21 UTC, tomesfilip commented on index.html
> +    <meta property="og:title" content="Majáles 2023" />
still 2023

2023-10-21 09:12 UTC, tomesfilip approved these changes

2023-10-21 09:13 UTC, merged